"""
File: Parsing of assembly files into our internal representation (TestCaseCode).
      This file contains ISA-independent code; see <isa>/<isa>_asm_parser.py for ISA-specific code.

Copyright (C) Microsoft Corporation
SPDX-License-Identifier: MIT

文件用途：汇编文件解析器。
将汇编文件解析为内部表示（TestCaseCode对象），包括：
- 预处理汇编文件（添加退出段、默认主函数、宏占位符、测量标记）
- 构建代码映射（段 -> 函数 -> 基本块 -> 指令）
- 解析每行汇编指令为Instruction对象
- 连接控制流（基本块之间的跳转和落下去关系）
- 正确性检查（着陆点、故障处理器、权限修改）

ISA无关代码在此文件中，ISA特定代码在<isa>/<isa>_asm_parser.py中。
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Dict, List, Final, Optional
from abc import ABC, abstractmethod
from collections import OrderedDict
import re
import os

from .tc_components.test_case_code import TestCaseProgram, Function, BasicBlock, TC_EXIT_LABEL
from .tc_components.instruction import Instruction, LabelOp, Operand, RegisterOp, MemoryOp, \
    ImmediateOp, AgenOp, CondOp, AnyOperand
from .instruction_spec import OT, InstructionSpec, OperandSpec
from .tc_components.actor import ActorPL, ActorMode
from .code_generator import assemble
from .config import CONF

if TYPE_CHECKING:
    from .target_desc import TargetDesc
    from .isa_spec import InstructionSet
    from .elf_parser import ELFParser
    from .code_generator import CodeGenerator

# 去除冗余空格的正则表达式（字母/数字后的空格保留）
RE_REDUNDANT_SPACES = re.compile(r"(?<![a-zA-Z0-9]) +")
# 退出标签行标识
TC_EXIT_LINE = TC_EXIT_LABEL + ":"


class AsmParserError(Exception):
    """
    Base exception class for AsmParser module

    汇编解析器模块的基础异常类。
    包含行号信息，便于定位解析错误。
    """

    def __init__(self, line_num: int, message: str) -> None:
        full_msg = f"[AsmParser] Error parsing assembly (line {line_num + 1}):\n{message}"
        super().__init__(full_msg)


def asm_parser_assert(condition: bool, line_number: int, explanation: str) -> None:
    """
    Raise an AsmParserError if the condition is not met

    条件断言函数：如果条件不满足则抛出AsmParserError。

    :param condition: 待检查的条件
    :param line_number: 关联的行号
    :param explanation: 错误说明
    """
    if not condition:
        raise AsmParserError(line_number, explanation)


@dataclass
class _ASMLine:
    """
    Metadata for a single line of assembly code

    汇编代码行的元数据类。
    存储原始行字符串、清理后的字符串、行号、补丁行号等信息。
    """

    def __init__(self, str_: str, line_num: int) -> None:
        self.str = str_  # 原始行字符串
        self.clean_str = str_.strip().lower()  # 去空白、转小写的清理字符串
        self.clean_str = RE_REDUNDANT_SPACES.sub("", self.clean_str)  # 去除冗余空格
        self.line_num = line_num  # 原始文件中的行号
        self.patched_line_num = 0  # 补丁后文件中的行号
        self.clean_line_num = 0  # 清理后的行号


# ==================================================================================================
# Private: Code Map Builder
# 私有：代码映射构建器
# ==================================================================================================
# 类型别名定义
_BBLabel = str  # 基本块标签
_BasicBlockMap = OrderedDict[_BBLabel, List[_ASMLine]]  # 基本块标签到指令行列表的映射
_FunctionName = str  # 函数名
_FunctionMap = OrderedDict[_FunctionName, _BasicBlockMap]  # 函数名到基本块映射的映射
_SectionLabel = str  # 段标签
_CodeMap = OrderedDict[_SectionLabel, _FunctionMap]  # 段标签到函数映射的映射


class _CodeMapBuilder:
    """
    Class responsible for building a dictionary of sections, functions, basic blocks,
    and relationships between them in an assembly file

    代码映射构建器。
    将汇编文件的行列表解析为段 -> 函数 -> 基本块的层级映射结构，
    识别行类型（段声明、函数标签、基本块标签、指令、宏）并组织到映射中。
    """

    section_label: Optional[str] = None  # 当前正在处理的段标签
    function_label: Optional[str] = None  # 当前正在处理的函数标签
    bb_label: Optional[str] = None  # 当前正在处理的基本块标签
    bb_is_autogenerated: bool = False  # 当前基本块是否为自动生成的默认块
    code_map: _CodeMap

    def create_code_map(self, lines: List[_ASMLine]) -> _CodeMap:
        """
        Parse lines and build a map of sections, functions, and basic blocks
        in the test case
        :param lines: representation of the assembly file as a list of ASMLine objects
        :return: a dictionary representing the code structure of the test case (_CodeMap)

        解析汇编行列表，构建段/函数/基本块的映射。

        逐行识别行类型，根据类型更新解析状态（当前段、函数、基本块），
        将指令行归入当前基本块，最终返回完整的代码映射。

        :param lines: 汇编文件的ASMLine对象列表
        :return: 代码映射字典（_CodeMap）
        """
        self.code_map: _CodeMap = OrderedDict()

        # Parse each line according to its type and accumulate the code structure as we go
        # 根据行类型逐行解析，累积代码结构
        for line_obj in lines:
            line_num = line_obj.line_num
            line = line_obj.clean_str
            type_ = self._get_line_type(line_obj)

            if type_ == "ignore":
                continue

            if type_ == "section":
                self._start_section(line_obj)
                continue

            if type_ == "function":
                self._start_function(line_obj)
                continue
            # 如果在段内但函数标签之前遇到指令，自动创建默认主函数
            if self.function_label is None and self.section_label is not None:
                self._create_default_main_function()  # allow for implicit functions

            if type_ == "basic_block":
                self._start_basic_block(line_obj)
                continue

            if type_ == "instruction":
                self._add_instruction(line_obj)
                continue

            if type_ == "opcode":
                self._add_instruction(_ASMLine("opcode", line_num))
                continue

            if type_ == "macro":
                # 将宏标签转换为伪指令格式
                str_ = self._macro_label_to_instr(line, line_num)
                self._add_instruction(_ASMLine(str_, line_num))

        return self.code_map

    def _get_line_type(self, line: _ASMLine) -> str:
        """
        根据行内容判断行类型。
        支持的类型：ignore, section, function, macro, opcode, basic_block, instruction
        """
        # pylint: disable=too-many-return-statements
        # NOTE: This is a selector, so it is expected to have many returns

        line_str = line.clean_str
        # 不以.开头的行视为指令
        if line_str[0] != ".":
            return "instruction"
        # 忽略全局声明和语法声明
        if line_str.startswith(".global") or line_str.startswith(".intel_syntax"):
            return "ignore"
        # .section为段声明
        if line_str.startswith(".section"):
            return "section"
        # .function_为函数标签
        if line_str.startswith(".function_"):
            return "function"
        # .macro为宏声明
        if line_str.startswith(".macro"):
            return "macro"
        # 数据声明指令（.bcd, .byte, .long, .quad等）
        if line_str[:4] == ".bcd " or line_str[:5] in [".byte", ".long", ".quad"] \
           or line_str[6:] in [".value", ".2byte", ".4byte", ".8byte"]:
            return "opcode"
        # 以冒号结尾的行是基本块标签
        if line_str[-1] == ":":
            return "basic_block"
        raise NotImplementedError(f"Line {line.line_num}: Unknown line type: {line_str}")

    def _start_section(self, line: _ASMLine) -> None:
        """
        开始解析一个新段。
        解析段标签格式 .section .data.<actor_name>，
        更新解析状态（当前段标签、重置函数和基本块标签）。
        """
        line_str = line.clean_str
        words = line.clean_str.split()
        assert len(words) == 2, \
            f"Line {line.line_num}: Invalid section label {line_str}; expected .section <label>"

        # exit section does not represent any actor; ignore it
        # exit段不代表任何参与者，忽略
        if words[1] == "exit":
            return

        # parse the section label
        # 解析段标签格式：.data.<actor_name>
        sub_words = words[1].split(".")
        assert len(sub_words) == 3, \
            f"Line {line.line_num}: Invalid section label: {line_str}"

        label = sub_words[2]
        assert label in CONF.get_actors_conf(), \
            f"Line {line.line_num}: Actor {label} was not defined in the config file"

        # update the parser state to reflect that a new section has started
        # 更新解析状态，开始新段
        if label not in self.code_map:
            self.code_map[label] = OrderedDict()
        self.section_label = label
        self.function_label = None  # 新段中函数标签重置
        self.bb_label = None  # 新段中基本块标签重置

    def _start_function(self, line: _ASMLine) -> None:
        """
        开始解析一个新函数。
        提取函数标签名，创建函数映射入口，
        并自动生成默认入口基本块。
        """
        assert self.section_label is not None, \
            f"Line {line.line_num}: Function started before a .section was declared"

        # get label
        # 提取函数标签（去掉末尾冒号）
        line_str = line.clean_str
        assert line_str[-1] == ":", f"Invalid function header: {line_str}"
        label = line_str[:-1]

        # update the parser state to reflect that a new function has started
        # 更新解析状态，开始新函数
        self.function_label = label
        self.code_map[self.section_label][label] = OrderedDict()

        # 自动创建默认入口基本块
        default_start_bb = ".bb_" + label.removeprefix(".function_") + ".entry"
        self.bb_label = default_start_bb
        self.bb_is_autogenerated = True
        self.code_map[self.section_label][label][default_start_bb] = []

    def _create_default_main_function(self) -> None:
        """
        当段中有指令但缺少函数标签时，自动创建默认主函数。
        使用段名和序号构造函数名和基本块名。
        """
        assert self.section_label is not None, \
            "Function started before a .section was declared"

        default_label = f".function_{self.section_label}_0"
        self.function_label = default_label
        self.code_map[self.section_label][default_label] = OrderedDict()

        default_start_bb = f".bb_{self.section_label}_0.entry"
        self.bb_label = default_start_bb
        self.bb_is_autogenerated = True
        self.code_map[self.section_label][default_label][default_start_bb] = []

    def _start_basic_block(self, line: _ASMLine) -> None:
        """
        开始解析一个新基本块。
        如果当前自动生成的默认基本块仍为空，则覆盖它；
        否则创建新的基本块映射入口。
        """
        assert self.section_label is not None, \
            f"Line {line.line_num}: Basic block started before a .section was declared"
        assert self.function_label is not None, \
            f"Line {line.line_num}: Basic block started before a .function was declared"
        assert self.bb_label is not None, \
            f"Line {line.line_num}: Default basic block was not created"

        # get label
        # 提取基本块标签（去掉末尾冒号）
        line_str = line.clean_str
        assert line_str[-1] == ":", f"Invalid basic block header: {line_str}"
        label = line_str[:-1]

        # overwrite default BB added to every function, if it is still empty
        # 如果自动生成的默认基本块仍为空，用实际标签覆盖它
        bb_map = self.code_map[self.section_label][self.function_label]
        if len(bb_map) == 1 and len(bb_map[self.bb_label]) == 0 \
           and self.bb_is_autogenerated:
            del self.code_map[self.section_label][self.function_label][self.bb_label]

        # update the parser state to reflect that a new basic block has started
        # 更新解析状态，开始新基本块
        self.bb_label = label
        self.bb_is_autogenerated = False
        assert label not in self.code_map[self.section_label][self.function_label], \
            f"Line {line.line_num}: Duplicate basic block label: {label}"
        self.code_map[self.section_label][self.function_label][label] = []

    def _add_instruction(self, line: _ASMLine) -> None:
        """
        将指令行添加到当前基本块的指令列表中。
        """
        assert self.section_label is not None, \
            f"Line {line.line_num}: Instruction found before a .section was declared"
        assert self.function_label is not None, \
            f"Line {line.line_num}: Instruction found before a .function was declared"
        assert self.bb_label is not None, \
            f"Line {line.line_num}: Instruction found before a basic block was declared"

        self.code_map[self.section_label][self.function_label][self.bb_label].append(line)

    def _macro_label_to_instr(self, line: str, line_num: int) -> str:
        """
        This function replaces label-like macros with a pseudo-instruction MACRO
        As such, we simplify further parsing of the test case

        将标签形式的宏转换为伪指令MACRO格式，简化后续解析。
        宏格式：.<macro_name>.<macro_id>.<args>: nop占位符
        转换为：macro .<macro_id>, .<args>

        :param line: 宏声明行字符串
        :param line_num: 行号
        :return: 转换后的伪指令字符串
        """
        # get rid of the NOP placeholder
        # 去除NOP占位符，分离宏标签和NOP部分
        words = line.split(":")
        asm_parser_assert(len(words) == 2, line_num, "Invalid macro declaration")
        asm_parser_assert(words[1][:3] == "nop", line_num, "Patching error")

        # get the macro name and its arguments
        # 解析宏名称和参数
        subwords = words[0].split(".")
        asm_parser_assert(len(subwords) >= 3, line_num, f"Invalid macro: {line}")
        asm_parser_assert(len(subwords) <= 7, line_num, f"Invalid macro: {line}")
        macro_id = subwords[2]  # 宏标识符
        args = '.'.join(subwords[3:])  # 宏参数
        if args:
            instr = f"macro .{macro_id}, .{args}"
        else:
            instr = f"macro .{macro_id}, .noarg"  # 无参数时使用.noarg

        return instr


# ==================================================================================================
# Private: Patching of assembly files
# 私有：汇编文件修补器
# ==================================================================================================
class _AsmPatcher:
    """
    汇编文件修补器。
    对汇编文件进行预处理，确保其格式可被解析器正确解析：
    - 添加退出段（.test_case_exit）
    - 添加默认主函数标签（如缺失）
    - 为宏添加NOP占位符
    - 添加默认测量标记（measurement_start/end）
    """

    _main_function_label: str = ""
    _macro_placeholder_str: Optional[str] = None

    def set_macro_placeholder(self, macro_placeholder_str: str) -> None:
        """
        Assign a string to be used as a placeholder for macro instructions.

        This method exist to allow re-use of the _AsmPatcher class between different ISAs.

        设置宏指令的NOP占位符字符串。
        此方法允许在不同ISA间复用_AsmPatcher类。

        :param macro_placeholder_str: 占位符字符串（如 "nop\n" 或 ARM64 的多条NOP）
        """
        assert self._macro_placeholder_str is None, \
            "Macro placeholder string was already set"
        self._macro_placeholder_str = macro_placeholder_str

    def patch_asm(self, asm_file: str, patched_asm_file: str) -> None:
        """
        Ensure that the assembly file is in the correct format for parsing:
        - all function labels are exposed by adding a global label
        - NOP is added at the end of each function to make size calculations easier
        - .function_0 is inserted at the beginning of the file if it is missing
        - .test_case_exit is within the .data.main section and contains a single NOP

        修补汇编文件使其格式正确可解析。
        依次执行：预清理 -> 添加退出段 -> 添加默认主函数 -> 添加宏占位符 -> 添加测量标记

        :param asm_file: 原始汇编文件路径
        :param patched_asm_file: 修补后的汇编文件路径
        """
        self._main_function_label = ""
        self._pre_clean(asm_file, patched_asm_file)

        # apply the patches
        # 依次应用各修补步骤
        self._add_exit_section(patched_asm_file)
        self._add_default_main(patched_asm_file)
        self._add_macro_placeholders(patched_asm_file)
        self._add_default_measurements(patched_asm_file)

    def _is_instruction(self, line: str) -> bool:
        """
        判断一行是否为指令（非注释、非空、非段声明等）。
        """
        return line != '' and line[0] not in ["#", "/"] \
            and (line[0] != '.' or line[:4] == ".bcd"
                 or line[:5] in [".byte", ".long", ".quad"] or line[:6] == '.macro'
                 or line[6:] in [".value", ".2byte", ".4byte", ".8byte"])

    def _pre_clean(self, asm_file: str, patched_asm_file: str) -> None:
        """
        预清理：去除每行空白并转小写。
        """
        with open(asm_file, "r") as f:
            with open(patched_asm_file, "w") as patched:
                for line in f:
                    line = line.strip().lower()
                    patched.write(line + "\n")

    def _add_exit_section(self, patched_asm_file: str) -> None:
        """
        确保退出段在正确的位置。
        .test_case_exit必须在.data.main段中，且只包含一个NOP。
        如果退出段不在正确位置，将其移到.data.main段内。
        """
        prev_line = ""
        with open(patched_asm_file, "r") as f:
            with open(patched_asm_file + ".tmp", "w") as patched:
                for line in f:
                    line = line[:-1]
                    if ".test_case_exit:" in line:
                        # 确保退出段在.data.main段内
                        if ".data.main" not in prev_line or "measurement_end" in prev_line:
                            patched.write(".section .data.main\n")
                        patched.write(".test_case_exit:" + "nop" + "\n")
                        continue
                    patched.write(line + "\n")
                    prev_line = line
        os.rename(patched_asm_file + ".tmp", patched_asm_file)

    def _add_default_main(self, patched_asm_file: str) -> None:
        """
        确保文件有主函数标签。
        如果文件中没有.function_标签，在第一个指令前插入.function_0。
        如果到达退出段仍未找到主函数，也在退出段前插入.function_0。
        """
        main_function_label = ""
        with open(patched_asm_file, "r") as f:
            with open(patched_asm_file + ".tmp", "w") as patched:
                for line in f:
                    line = line[:-1]

                    # if we already have a main function, just copy the rest of the file
                    # 已找到主函数，直接复制后续内容
                    if main_function_label:
                        patched.write(line + "\n")
                        continue

                    # reached the end of the file
                    # 到达文件末尾（退出段），插入默认主函数
                    if ".test_case_exit:" in line:
                        main_function_label = ".function_0"
                        patched.write(".function_0:\n")
                        patched.write(line + "\n")
                        continue

                    # found the main function
                    # 找到主函数标签
                    if line.startswith(".function_"):
                        main_function_label = line[:-1]
                        patched.write(line + "\n")
                        continue

                    # found an instruction before the main function
                    # 在主函数标签之前遇到指令，插入默认主函数标签
                    if self._is_instruction(line):
                        patched.write(".function_0:\n")
                        main_function_label = ".function_0"
                        patched.write(line + "\n")
                        continue

                    # copy non-instruction lines
                    # 复制非指令行
                    patched.write(line + "\n")

        # 记录主函数标签名，供后续修补步骤使用
        self._main_function_label = main_function_label
        os.rename(patched_asm_file + ".tmp", patched_asm_file)

    def _add_macro_placeholders(self, patched_asm_file: str) -> None:
        """
        add NOP placeholders after macros

        为宏声明添加NOP占位符。
        宏声明行必须以NOP结尾，以便ELF解析器计算宏的大小。
        如果宏行缺少NOP，追加占位符字符串。
        """
        assert self._macro_placeholder_str is not None, \
            "set_macro_placeholder() was not called before patching"

        with open(patched_asm_file, "r") as f:
            with open(patched_asm_file + ".tmp", "w") as patched:
                for line in f:
                    line = line.lower()
                    if line.startswith(".macro"):
                        if "nop" not in line:
                            # 宏行缺少NOP，追加占位符
                            patched.write(line[:-1] + self._macro_placeholder_str + "\n")
                        else:
                            # 宏行已有占位符NOP，验证格式正确
                            assert self._macro_placeholder_str in line, \
                                "Unexpected NOP placeholder: " + line
                            patched.write(line)
                    else:
                        patched.write(line)
        os.rename(patched_asm_file + ".tmp", patched_asm_file)

    def _add_default_measurements(self, patched_asm_file: str) -> None:
        """
        添加默认测量标记宏。
        如果文件缺少measurement_start，在主函数标签后添加；
        如果缺少measurement_end，在退出段前添加。
        """
        assert self._macro_placeholder_str is not None, \
            "set_macro_placeholder() was not called before patching"

        # identify if the file already has the measurement macros;
        # this information is used by multiple patching steps
        # 检测文件中是否已有测量宏
        has_measurement_start = False
        has_measurement_end = False
        with open(patched_asm_file, "r") as f:
            for line in f:
                line = line.lower()
                if line.startswith(".macro.measurement_start"):
                    has_measurement_start = True
                elif line.startswith(".macro.measurement_end"):
                    has_measurement_end = True

        # add .macro.measurement_start after .function_0
        # 在主函数标签后添加measurement_start宏
        if not has_measurement_start:
            with open(patched_asm_file, "r") as f:
                with open(patched_asm_file + ".tmp", "w") as patched:
                    for line in f:
                        line = line.lower()
                        patched.write(line)
                        if line.startswith(self._main_function_label):
                            patched.write(".macro.measurement_start:" + self._macro_placeholder_str
                                          + "\n")
            os.rename(patched_asm_file + ".tmp", patched_asm_file)

        # add .macro.measurement_end before .test_case_exit
        # 在退出段前添加measurement_end宏
        if not has_measurement_end:
            with open(patched_asm_file, "r") as f:
                with open(patched_asm_file + ".tmp", "w") as patched:
                    prev_line = ""
                    for line in f:
                        line = line.lower()
                        if line.startswith(".test_case_exit:"):
                            if prev_line.startswith(".section"):
                                # 退出段前是段声明时，添加函数结束标签
                                patched.write(".function_end:\n")
                            patched.write(".macro.measurement_end:" + self._macro_placeholder_str
                                          + "\n")
                        patched.write(line)
                        prev_line = line
            os.rename(patched_asm_file + ".tmp", patched_asm_file)


# ==================================================================================================
# Public (intended for <isa>/asm_parser.py): Line parsing
# 公共接口（供ISA特定asm_parser.py使用）：行解析
# ==================================================================================================
class AsmLineParser(ABC):
    """
    Class responsible for parsing an assembly line into an Instruction object.

    This class is a common ISA-independent functionality with hooks to be implemented by
    ISA-specific subclasses.

    汇编行解析器。
    将单行汇编代码解析为Instruction对象，提供ISA无关的基础功能，
    ISA特定的解析逻辑（分词、指令名提取、操作数提取、规范匹配）
    由子类通过抽象方法实现。
    """
    _instruction_map: Final[Dict[str, List[InstructionSpec]]]
    _curr_ln: int
    _comment_char: str  # set by subclasses — ISA特定注释字符，由子类设置

    def __init__(self, isa_spec: InstructionSet, target_desc: TargetDesc) -> None:
        """
        初始化行解析器，构建指令映射表。

        :param isa_spec: 指令集规范
        :param target_desc: 目标架构描述
        """
        self._instruction_map = self._build_instruction_map(isa_spec)
        self._target_desc = target_desc
        self._curr_ln = -1

    # ----------------------------------------------------------------------------------------------
    # Hooks for ISA-specific subclasses
    # ISA特定子类需实现的钩子方法
    @abstractmethod
    def _tokenize(self, line: str) -> List[str]:
        """ Tokenize the line and store the results internally — 分词：将汇编行拆分为词元列表 """

    @abstractmethod
    def _get_instruction_name(self, line: str, tokens: List[str]) -> str:
        """ Get the instruction name from the line, based on the tokenized data — 从分词结果提取指令名 """

    @abstractmethod
    def _get_instruction_operands(self, line: str, name: str, tokens: List[str]) -> List[str]:
        """ Get the instruction operands from the line, based on the tokenized data — 从分词结果提取操作数列表 """

    @abstractmethod
    def _get_initial_candidate_specs(self, line: str, name: str) -> List[InstructionSpec]:
        """ Get a list of candidate specs for the given assembly line — 获取候选指令规范列表 """

    @abstractmethod
    def _check_if_spec_matches(self, spec: InstructionSpec, operands_raw: List[str]) -> bool:
        """ Check if the given spec matches the given list of operand strings — 检查规范是否匹配操作数列表 """

    # ----------------------------------------------------------------------------------------------
    # Common ISA-independent Functionality
    # ISA无关的通用功能
    @staticmethod
    def _build_instruction_map(isa_spec: InstructionSet) -> Dict[str, List[InstructionSpec]]:
        """
        构建指令名到规范列表的映射表。
        一个指令名可能对应多个规范（不同操作数组合）。
        同时注册opcode和macro伪指令规范。
        """
        instruction_map: Dict[str, List[InstructionSpec]] = {}
        for spec in isa_spec.instructions_unfiltered:
            if spec.name in instruction_map:
                instruction_map[spec.name].append(spec)
            else:
                instruction_map[spec.name] = [spec]

            # add an entry for direct opcodes
            # 添加opcode伪指令规范
            opcode_spec = InstructionSpec("opcode", "opcode")
            instruction_map["opcode"] = [opcode_spec]

            # entry for macros
            # 添加macro伪指令规范
            macro_spec = InstructionSpec("macro", "macro")
            macro_spec.operands = [
                OperandSpec([], OT.LABEL, False, False),
                OperandSpec([], OT.LABEL, False, False)
            ]
            instruction_map["macro"] = [macro_spec]
        return instruction_map

    def parse_line(self, line: str, line_num: int) -> Instruction:
        """
        Implementation of the AsmLineParser interface for x86 assembly lines (Intel syntax)

        解析单行汇编代码为Instruction对象的完整流程：
        1. 识别行类型（是否为插桩/不可移除指令）
        2. 移除注释
        3. 分词并提取指令名和操作数
        4. 匹配指令规范
        5. 创建指令对象

        :param line: 汇编行字符串
        :param line_num: 行号
        :return: 解析生成的Instruction对象
        """
        self._curr_ln = line_num

        # Identify the line type
        # 识别指令属性：是否为插桩指令或不可移除指令
        line = line.lower()
        is_instrumentation = "instrumentation" in line
        is_noremove = "noremove" in line

        # Remove comments
        # 移除注释部分
        if self._comment_char in line:
            line = line.split(self._comment_char)[0].strip()

        # Get instruction name and operands
        # 获取指令名和操作数
        tokens = self._tokenize(line)
        name = self._get_instruction_name(line, tokens)
        operands_raw = self._get_instruction_operands(line, name, tokens)

        # Find a matching spec
        # 查找匹配的指令规范
        spec = self._find_matching_spec(line, name, operands_raw)

        # generate a corresponding Instruction
        # 根据规范和操作数创建Instruction对象
        inst = self._create_instruction(spec, operands_raw, is_instrumentation, is_noremove)
        inst.assign_line_num(line_num)

        return inst

    def _find_matching_spec(self, line: str, name: str, operands_raw: List[str]) -> InstructionSpec:
        """
        Find the InstructionSpec that matches the given assembly line

        查找与汇编行匹配的指令规范。
        1. 获取候选规范列表
        2. 过滤出与操作数匹配的规范
        3. 如有多个匹配，优先选择有魔法值的规范
        4. 返回最终匹配的规范（如有多个等效规范取第一个）

        :param line: 汇编行字符串
        :param name: 指令名
        :param operands_raw: 操作数原始字符串列表
        :return: 匹配的指令规范
        """

        # Get candidate specs
        # 获取候选规范
        specs = self._get_initial_candidate_specs(line, name)
        if len(specs) == 0:
            raise AsmParserError(self._curr_ln, f"Unknown instruction {line}")

        # find a matching spec
        # 过滤出与操作数匹配的规范
        matching_specs: List[InstructionSpec] = []
        for spec_candidate in specs:
            if self._check_if_spec_matches(spec_candidate, operands_raw):
                matching_specs.append(spec_candidate)
        if len(matching_specs) == 0:
            raise AsmParserError(self._curr_ln, f"Could not find a matching spec for {line}")

        # we might find several matches if the instruction has a magic operand value
        # 如果有多个匹配，优先选择有魔法值（特殊操作数值）的规范
        if len(matching_specs) > 1:
            magic_value_specs = list(filter(lambda x: (x.has_magic_value), matching_specs))
            if magic_value_specs:
                matching_specs = magic_value_specs

        # at this point we should have only one spec, but even if we don't, all of them should
        # be equivalent. Just pick the first
        # 取第一个规范（多个等效规范时任意选择）
        return matching_specs[0]

    def _create_instruction(self, spec: InstructionSpec, operands_raw: List[str],
                            is_instrumentation: bool, is_noremove: bool) -> Instruction:
        """
        Create an Instruction object and its operands based on the assembly line
        and the spec that describes the instruction

        根据指令规范和操作数原始字符串创建Instruction对象。
        为每个操作数创建对应类型的操作数对象（REG/MEM/IMM/LABEL/COND/AGEN），
        并添加隐式操作数。

        :param spec: 指令规范
        :param operands_raw: 操作数原始字符串列表
        :param is_instrumentation: 是否为插桩指令
        :param is_noremove: 是否不可移除
        :return: 创建的Instruction对象
        """
        # create the instruction with no operands
        # 创建无操作数的指令骨架
        inst = Instruction.from_spec(
            spec, is_instrumentation=is_instrumentation, is_noremove=is_noremove)

        # create operands
        # 为每个操作数创建对应类型的操作数对象
        op: AnyOperand
        for op_id, op_raw in enumerate(operands_raw):
            op_spec = spec.operands[op_id]
            if op_spec.type == OT.REG:
                op = RegisterOp(op_raw, op_spec.width, op_spec.src, op_spec.dest)
            elif op_spec.type == OT.MEM:
                # 内存操作数：提取方括号内的地址表达式
                address_match = re.search(r'\[(.*)\]', op_raw)
                asm_parser_assert(address_match is not None, self._curr_ln,
                                  "Invalid memory address")
                address = address_match.group(1)  # type: ignore
                op = MemoryOp(address, op_spec.width, op_spec.src, op_spec.dest)
            elif op_spec.type == OT.IMM:
                op = ImmediateOp(op_raw, op_spec.width)
            elif op_spec.type == OT.LABEL:
                # 标签操作数：仅控制流指令和宏使用
                assert spec.is_control_flow or spec.name == "macro"
                op = LabelOp(op_raw)
            elif op_spec.type == OT.COND:
                op = CondOp(op_raw)
            else:  # AGEN — 地址生成操作数
                address_match = re.search(r'\[(.*)\]', op_raw)
                asm_parser_assert(address_match is not None, self._curr_ln,
                                  "Invalid memory address")
                address = address_match.group(1)  # type: ignore
                op = AgenOp(address, op_spec.width)
            inst.operands.append(op)
        # add implicit operands
        # 添加隐式操作数（如标志寄存器等，从固定规范创建）
        for op_spec in spec.implicit_operands:
            # implicit operands should always have fixed spec, hence it's safe to use
            # the from_fixed_spec constructor
            op = Operand.from_fixed_spec(op_spec)
            inst.implicit_operands.append(op)
        return inst


# ==================================================================================================
# Public: High-level ASM Parser
# 公共接口：高层汇编解析器
# ==================================================================================================
class AsmParser(ABC):
    """
    Class responsible for parsing (and optionally patching) assembly files
    and producing TestCaseCode objects from them

    高层汇编解析器。
    完整流程：读取汇编文件 -> 修补格式 -> 构建代码映射 -> 填充测试用例结构 ->
    连接控制流 -> 正确性检查 -> 编译和ELF解析
    """

    _target_desc: Final[TargetDesc]
    _isa_spec: Final[InstructionSet]
    _asm_patcher: _AsmPatcher
    _line_parser: AsmLineParser
    _lines: List[_ASMLine]

    def __init__(self, isa_spec: InstructionSet, target_desc: TargetDesc) -> None:
        """
        初始化汇编解析器。

        :param isa_spec: 指令集规范
        :param target_desc: 目标架构描述
        """
        self._isa_spec = isa_spec
        self._target_desc = target_desc
        self._asm_patcher = _AsmPatcher()

    # ----------------------------------------------------------------------------------------------
    # Public Interface
    # 公共接口
    def parse_file(self,
                   asm_file: str,
                   generator: CodeGenerator,
                   elf_parser: ELFParser,
                   is_template: bool = False) -> TestCaseProgram:
        """
        Read a test case from a file, patch it to make it parsable (if necessary),
        create a complete TestCaseCode object based on it, and populate it with ELF data.

        This function is used instead of ProgramGenerator.create_test_case() when Revizor works
        with a user-provided test case. Hence, this function's output is expected to be
        equivalent to the output of ProgramGenerator.create_test_case().

        :param asm_file: path to the input assembly file to parse
        :param generator: an instance of ProgramGenerator object to assist in creating the test case
        :param elf_parser: an instance of ELFParser object to assist in creating the test case
        :return: a fully constructed TestCaseCode object

        从文件解析测试用例的完整流程。

        步骤：
        1. 读取原始文件并创建ASMLine对象列表
        2. 修补汇编文件格式
        3. 更新行号映射（修补后行号与原始行号的对应）
        4. 清理行列表（去注释、空行）
        5. 构建代码映射（段/函数/基本块结构）
        6. 创建空测试用例并设置参与者
        7. 根据代码映射填充测试用例结构
        8. 连接控制流
        9. 处理空测试用例
        10. 正确性检查
        11. 编译和ELF解析（非模板模式）

        :param asm_file: 输入汇编文件路径
        :param generator: 代码生成器实例（用于创建参与者等）
        :param elf_parser: ELF解析器实例
        :param is_template: 是否为模板文件（模板不编译和解析ELF）
        :return: 完整构建的TestCaseProgram对象
        """
        # Transform the input file into a list of ASMLine objects
        # 读取文件，创建ASMLine对象列表
        with open(asm_file, 'r') as f:
            dirty_lines = [_ASMLine(l, i) for i, l in enumerate(f)]

        # Apply patches to the assembly file to make it parsable
        # 修补汇编文件，使其格式可被解析
        patched_asm_file = asm_file + ".patched.asm"
        self._patch_asm(asm_file, patched_asm_file)
        dirty_lines = self._update_lines_after_patch(patched_asm_file, dirty_lines)

        # Build a map of the code structure
        # 清理行列表并构建代码映射
        clean_lines = self._get_clean_lines(dirty_lines)
        code_map = _CodeMapBuilder().create_code_map(clean_lines)

        # Create an empty test case with actors set up according to the configuration
        # 创建空测试用例，按配置设置参与者
        test_case = TestCaseProgram(patched_asm_file)
        generator.generate_actors_with_sections(test_case, CONF.get_actors_conf())

        # Fill the test case with the object representations of the parsed assembly
        # 根据代码映射填充测试用例结构（段、函数、基本块、指令）
        self._fill_test_case_structure(test_case, code_map)
        assert len(test_case) > 0, "Default section not found"
        # 连接控制流（基本块之间的跳转关系）
        self._connect_control_flow(test_case)

        # Handle empty and trivial assembly files
        # 处理空或极简的汇编文件
        if len(test_case) == 1 and len(test_case[0]) == 0 and len(test_case[0][0]) == 0:
            self._handle_empty_test_case(test_case)

        # Perform final correctness checks
        # 执行正确性检查
        self._check_test_case_correctness(test_case)

        # Assemble the test case and populate with ELF data
        # 编译并解析ELF数据（模板模式跳过此步骤）
        if not is_template:  # there is no point in assembling a template
            test_case.assign_obj(asm_file[:-4] + ".o")
            assemble(test_case)
            elf_parser.populate_elf_data(test_case.get_obj(), test_case)

        return test_case

    # ----------------------------------------------------------------------------------------------
    # Private: Assembly Patching
    # 私有：汇编文件修补
    def _patch_asm(self, asm_file: str, patched_asm_file: str) -> None:
        """ 调用修补器修补汇编文件 """
        return self._asm_patcher.patch_asm(asm_file, patched_asm_file)

    def _update_lines_after_patch(self, patched_asm_file: str,
                                  org_lines: List[_ASMLine]) -> List[_ASMLine]:
        """
        Create a list of ASMLine objects from the patched assembly file, such that
        the line number correspond to the original assembly file if the line was not patched

        从修补后的文件创建ASMLine列表，保持与原始文件的行号对应。
        逐行比较修补后行和原始行，匹配的行使用原始行号。

        :param patched_asm_file: 修补后的汇编文件路径
        :param org_lines: 原始文件的ASMLine列表
        :return: 修补后的ASMLine列表（保留原始行号）
        """

        patched_lines = []
        with open(patched_asm_file, 'r') as patched:
            org_line_num = 0
            for patched_line_num, p_line in enumerate(patched):
                o_line_obj = org_lines[org_line_num]
                o_line = o_line_obj.str.strip().lower()

                p_line = p_line.strip().lower()
                p_line_obj = _ASMLine(p_line, 0)
                p_line_obj.patched_line_num = patched_line_num

                # 如果修补行包含原始行内容，使用原始行号
                if o_line in p_line:
                    p_line_obj.line_num = o_line_obj.line_num
                    org_line_num += 1

                patched_lines.append(p_line_obj)
        return patched_lines

    # ----------------------------------------------------------------------------------------------
    # Private: Line Parsing
    # 私有：行解析
    def _get_clean_lines(self, org_lines: List[_ASMLine]) -> List[_ASMLine]:
        """
        Remove comments and empty lines from a list of ASMLine objects

        清理ASMLine列表：移除注释、空行和退出标签后的所有内容。

        :param org_lines: 原始ASMLine列表
        :return: 清理后的ASMLine列表
        """
        self._validate_dirty_lines(org_lines)

        lines = []
        finished = False  # 是否已到达退出标签
        for line_obj in org_lines:
            line_str = line_obj.str

            # Skip comments and empty lines
            # 跳过注释和空行
            if not line_str or line_str[0] in ["", "#", "/"]:
                continue

            # Skip lines after test case exit
            # 跳过退出标签后的所有行
            if line_str[:16] == TC_EXIT_LINE:
                finished = True
                continue
            if finished:
                continue

            # Save all other lines
            # 保留其他行
            lines.append(line_obj)

        return lines

    def _validate_dirty_lines(self, lines: List[_ASMLine]) -> None:
        """
        Check that the list of lines is well-formed

        验证ASMLine列表格式正确性：
        - 确保退出标签存在
        - 确保退出标签后无指令

        :param lines: 待验证的ASMLine列表
        """
        finished = False
        for line_obj in lines:
            line_str = line_obj.clean_str
            if not line_str:
                continue
            if line_str[:16] == TC_EXIT_LINE:
                finished = True
                continue

            # Check that there are no instructions after .test_case_exit
            # 检查退出标签后不应有指令
            if finished and line_str[0] not in ["", ".", "#", "/"]:
                raise AsmParserError(line_obj.line_num,
                                     f"Found instructions after .test_case_exit: {line_obj.str}")

        if not finished:
            raise AsmParserError(0, ".test_case_exit not found")

    def _parse_line(self, line: str, line_num: int) -> Instruction:
        """ 调用行解析器解析单行汇编 """
        return self._line_parser.parse_line(line, line_num)

    # ----------------------------------------------------------------------------------------------
    # Private: Building Test Case Structure
    # 私有：构建测试用例结构
    def _fill_test_case_structure(self, test_case: TestCaseProgram, code_map: _CodeMap) -> None:
        """
        Initialize the structure of the test case according to the code map.
        The function fills the test case with sections, functions, basic blocks,
        instructions, and connects them
        :param test_case: the test case to be filled
        :param code_map: the code map representing the structure of the parsed assembly
        :return: None

        根据代码映射填充测试用例的结构层级：段 -> 函数 -> 基本块 -> 指令。
        同时区分普通指令和终止指令（控制流指令放在terminators列表中）。

        :param test_case: 待填充的测试用例
        :param code_map: 代码映射字典
        """
        for section_name, function_map in code_map.items():
            section = test_case.find_section(name=section_name)

            for func_name, bb_map in function_map.items():
                func = Function(func_name, section)
                section.append(func)

                for bb_name, inst_lines in bb_map.items():
                    # print(">>", bb_name)
                    bb = BasicBlock(bb_name, func)
                    func.append(bb)

                    # 控制流指令之后的指令都是终止指令
                    terminators_started = False
                    for line in inst_lines:
                        # print(f"    {line}")
                        inst = self._parse_line(line.clean_str, line.line_num)
                        if not inst.is_control_flow:
                            # 非控制流指令放在基本块指令列表中
                            assert not terminators_started, \
                                f"Line {line.line_num}: Terminator not at the end of BB"
                            bb.insert_after(bb.get_last(), inst)
                            continue

                        # 控制流指令放在终止指令列表中
                        terminators_started = True
                        bb.terminators.append(inst)

    def _connect_control_flow(self, test_case: TestCaseProgram) -> None:
        """
        Connect the basic blocks in the test case by following their terminators
        :param test_case: the test case to connect
        :return: None

        连接测试用例中的控制流：根据终止指令确定基本块之间的后继关系。

        连接规则：
        - 落下去（fallthrough）：如果前一个基本块的最后一个终止指令不是无条件跳转，
          则前一个基本块有一个落下去后继指向当前基本块
        - 跳转（taken branch）：终止指令中的标签操作数指向目标基本块
        - 函数调用（call）不建立基本块后继关系

        :param test_case: 待连接控制流的测试用例
        """
        # connect basic blocks
        # 构建基本块名到对象的映射
        bb_names = {bb.name.lower(): bb for func in test_case.iter_functions() for bb in func}
        bb_names[TC_EXIT_LABEL] = test_case.get_tc_exit_bb()
        previous_bb = None
        for func in test_case.iter_functions():
            for bb in func:
                # fallthrough — 落下去连接
                if previous_bb:  # skip the first BB
                    # there is a fallthrough only if the last terminator is not a direct jump
                    # 只有当最后一个终止指令不是无条件跳转时，才存在落下去后继
                    if not previous_bb.terminators or \
                       not self._target_desc.is_unconditional_branch(previous_bb.terminators[-1]):
                        previous_bb.successors.append(bb)
                previous_bb = bb

                # taken branches — 跳转连接
                for terminator in bb.terminators:
                    # skip calls as they target functions, not basic blocks
                    # 跳过函数调用（call的目标是函数而非基本块）
                    if self._target_desc.is_call(terminator):
                        continue

                    for op in terminator.operands:
                        if isinstance(op, LabelOp):
                            asm_parser_assert(op.value in bb_names, -1, "Unknown label " + op.value)
                            successor = bb_names[op.value]
                            bb.successors.append(successor)

            # last BB always falls through to the exit
            # 函数最后一个基本块总是落下去到退出节点
            func[-1].successors.append(func.get_exit_bb())

    def _handle_empty_test_case(self, test_case: TestCaseProgram) -> None:
        """
        处理空测试用例：创建包含单个NOP指令的最小函数和基本块。
        """
        main = Function(".function_0", test_case.find_section(name="main"))
        test_case[0].append(main)

        bb = BasicBlock(".bb_0", main)
        main.append(bb)

        instr = Instruction("nop", "BASE-NOP")
        bb.insert_after(bb.get_last(), instr)
        bb.successors.append(main.get_exit_bb())

    # ----------------------------------------------------------------------------------------------
    # Private: Correctness Checks
    # 私有：正确性检查
    def _check_test_case_correctness(self, test_case: TestCaseProgram) -> None:
        """
        Check that the TestCaseCode object created from the assembly file is correct

        检查从汇编文件创建的测试用例对象的正确性。
        包含三个检查：着陆点、故障处理器、权限修改。
        """
        self._check_landing_sites(test_case)
        self._check_fault_handler(test_case)
        self._check_set_data_permission(test_case)

    def _check_landing_sites(self, test_case: TestCaseProgram) -> None:
        """
        check that all actor switch macros have landing sites

        检查所有参与者切换宏（set_k2u/u2k/h2g/g2h_target）都有对应的着陆点宏。
        每个切换宏的目标函数的第一个基本块必须包含匹配的landing宏。

        :param test_case: 待检查的测试用例
        """
        # pylint: disable=too-many-branches
        # NOTE: there are many checks to be performed on the set_* family of macros, so
        # having many branches is expected

        # 参与者切换宏列表
        switch_labels = [".set_k2u_target", ".set_u2k_target", ".set_h2g_target", ".set_g2h_target"]
        switches = []
        for func in test_case.iter_functions():
            for bb in func:
                for inst in bb:
                    if inst.name == "macro" and inst.operands[0].value in switch_labels:
                        switches.append(inst)

        for switch in switches:
            # 提取切换宏的目标函数名
            target = switch.operands[1].value.split(".")[2]
            for func in test_case.iter_functions():
                stripped_name = func.name[1:]
                if stripped_name == target:
                    target_function = func
                    break
            else:
                raise AsmParserError(-1, f"Macro {switch} targets a non-existing function")

            # 检查目标函数的第一个基本块是否包含着陆点宏
            first_bb = target_function.get_first_bb()
            assert first_bb is not None, f"Macro {switch} targets a function without basic blocks"
            first_node = first_bb.get_first()
            assert first_node is not None, f"Macro {switch} targets a basic block without a landing"
            if not first_node.instruction.operands or \
               "landing" not in first_node.instruction.operands[0].value:
                raise AsmParserError(-1, f"{switch} does not target a landing site macro")
            target_name = first_node.instruction.operands[0].value

            # 验证着陆点类型与切换宏类型匹配
            if switch.operands[0].value == ".set_k2u_target" and target_name != ".landing_k2u":
                raise AsmParserError(switch.line_num(), f"{switch} does not target landing_k2u")
            if switch.operands[0].value == ".set_u2k_target" and target_name != ".landing_u2k":
                raise AsmParserError(switch.line_num(), f"{switch} does not target landing_u2k")
            if switch.operands[0].value == ".set_h2g_target" and target_name != ".landing_h2g":
                raise AsmParserError(switch.line_num(), f"{switch} does not target landing_h2g")
            if switch.operands[0].value == ".set_g2h_target" and target_name != ".landing_g2h":
                raise AsmParserError(switch.line_num(), f"{switch} does not target landing_g2h")

    def _check_fault_handler(self, test_case: TestCaseProgram) -> None:
        """
        check that there is at most one fault handler

        检查测试用例中最多只有一个故障处理器宏（.fault_handler）。
        """
        n_fault_handlers = 0
        for func in test_case.iter_functions():
            for bb in func:
                for inst in bb:
                    if inst.name == "macro" and inst.operands[0].value == ".fault_handler":
                        n_fault_handlers += 1
                    if n_fault_handlers > 1:
                        raise AsmParserError(inst.line_num(), "Found more than one fault handler")

    def _check_set_data_permission(self, test_case: TestCaseProgram) -> None:
        """
        check that PT modification happens only in kernel host mode

        检查页表权限修改宏（.set_data_permissions）只在内核宿主模式下使用。
        此宏涉及特权级操作，不应在用户态或客户模式下使用。
        """
        for sec in test_case:
            owner = sec.owner
            for func in sec:
                for bb in func:
                    for inst in bb:
                        if inst.name == "macro" \
                           and inst.operands[0].value == ".set_data_permissions":
                            asm_parser_assert(
                                owner.privilege_level == ActorPL.KERNEL
                                and owner.mode == ActorMode.HOST, inst.line_num(),
                                "PT modification is allowed only in kernel host mode")
