"""
文件：表示测试用例数据（即输入）及其相关和派生类的类集合。

本模块定义了InputData类（测试用例的输入数据）和InputTaint类（输入数据的污点标记）。
InputData是基于numpy.ndarray的固定大小数组，用于化沙箱内存和寄存器。
InputTaint是布尔数组，标记哪些输入元素影响了合约追踪结果。

File: Classes representing test case data (aka input), as well as related and derived classes.

Copyright (C) Microsoft Corporation
SPDX-License-Identifier: MIT
"""
from __future__ import annotations
from typing import TYPE_CHECKING, Tuple, Optional, List
import numpy as np

from ..sandbox import SandboxLayout, DataArea

if TYPE_CHECKING:
    from .actor import ActorID

InputID = int  # 输入ID类型

# ==================================================================================================
# 每个参与者的输入数据
# Per-actor input data
# ==================================================================================================

# _ActorInput数据类型表示单个参与者的输入数据结构
# 各区域与沙箱布局(SandboxLayout)中的可化数据区域对应
_ActorInput = np.dtype(
    [
        ('main', np.uint64, SandboxLayout.data_area_size(DataArea.MAIN) // 8),
        # 主数据区域：存储参与者的主要数据
        ('faulty', np.uint64, SandboxLayout.data_area_size(DataArea.FAULTY) // 8),
        # 故障数据区域：存储可能导致故障的数据
        ('gpr', np.uint64, SandboxLayout.data_area_size(DataArea.GPR) // 8),
        # 通用寄存器区域：存储通用寄存器初始值
        ('simd', np.uint64, SandboxLayout.data_area_size(DataArea.SIMD) // 8),
        # SIMD寄存器区域：存储SIMD寄存器初始值
        ('padding', np.uint64, SandboxLayout.data_area_size(DataArea.OVERFLOW_PAD) // 8),
        # 填充区域：用于溢出保护，不被化
    ],
    align=False,
)

# 计算每个参与者的数据大小（不包括padding）
_ACTOR_DATA_SIZE = _ActorInput['main'].itemsize + _ActorInput['faulty'].itemsize + \
    _ActorInput['gpr'].itemsize + _ActorInput['simd'].itemsize

# ==================================================================================================
# 完整输入数据
# Full input data
# ==================================================================================================
UINT_NDARRAY = np.ndarray[Tuple[int, ...], np.dtype[np.uint64]]


class InputData(UINT_NDARRAY):
    """
    表示测试用例程序(TestCaseCode)的单个数据输入类。

    该数据由执行器和模型用来化沙箱内存和寄存器。
    输入通常由输入生成器生成或从二进制文件解析。

    内部实现为固定大小的numpy.ndarray（64位无符号整数数组），
    并添加了一些便捷方法。

    数组按参与者ID排序，组织为1维的_ActorInput结构数组（每个参与者一个）。
    每个_ActorInput结构包含单个参与者的输入数据，其布局与sandbox.py:SandboxLayout
    的可化数据区域布局一致。

    Input数组组织如下：
    |-----|-------------------------------| main
    | A   | sizeof(DataArea.MAIN)         |
    | C   |-------------------------------| faulty
    | T   | sizeof(DataArea.FAULTY)       |
    | O   |-------------------------------| gpr
    | R   | sizeof(DataArea.GPR)          |
    |     |-------------------------------| simd
    | 0   | sizeof(DataArea.SIMD)         |
    |     |-------------------------------| padding
    |     | sizeof(DataArea.OVERFLOW_PAD) |
    |-----|-------------------------------|
    | ... (重复n_actors次)

    可通过数组接口访问各区域数据，例如：
    actor0_main = Input[0]['main']

    数组大小等于参与者数量乘以_ActorInput中的元素数量：
    Input.size = n_actors * _ActorInput.size

    Class representing a single data input for a test case program (TestCaseCode).
    This data is used by the executor and the model to initialize the sandbox memory and registers.
    The input is typically generated by the input generator or parsed from a binary file.

    Internally, this class is a fixed-size numpy.ndarray of 64-bit unsigned integers,
    with a few addition methods for convenience.

    The array is organized as a 1D array of _ActorInput structures (one for each actor in the test
    case program), sorted by actor ID. Each _ActorInput structure contains the input data for a
    single actor, and it's layout mirrors the layout of the initialiable data regions
    of the sandbox.py:SandboxLayout.
    Namely, the Input array is organized as follows:

    |-----|-------------------------------| main
    | A   | sizeof(DataArea.MAIN)         |
    | C   |-------------------------------| faulty
    | T   | sizeof(DataArea.FAULTY)       |
    | O   |-------------------------------| gpr
    | R   | sizeof(DataArea.GPR)          |
    |     |-------------------------------| simd
    | 0   | sizeof(DataArea.SIMD)         |
    |     |-------------------------------| padding
    |     | sizeof(DataArea.OVERFLOW_PAD) |
    |-----|-------------------------------|
    | ... (repeat for n_actors)

    The data in each region could be accesses via the array interface, e.g.,
    actor0_main = Input[0]['main']

    The array size is equal to the number of actors multiplied by
    the number of elements in _ActorInput, i.e.,
        Input.size = n_actors * _ActorInput.size
    """

    seed: int = 0
    """ 生成此输入所使用的种子值 """

    # ==============================================================================================
    # 构造函数
    # Constructors

    def __new__(cls, n_actors: int = 1) -> InputData:
        """
        创建指定参与者数量的输入数据数组。

        :param n_actors: 参与者数量，默认为1
        :return: InputData对象
        """
        obj = super().__new__(cls, (n_actors,), _ActorInput, None, 0, None, None)
        return obj

    def __array_finalize__(self, obj: Optional[UINT_NDARRAY]) -> None:  # type: ignore
        # numpy数组继承所需的finalize方法
        # if obj is None:
        #     return
        pass

    # ==============================================================================================
    # 类接口
    # Class interface

    @classmethod
    def data_size_per_actor(cls) -> int:
        """
        获取单个参与者的数据区域大小（字节）。

        :return: 大小（字节）

        Get the size (in bytes) of the data area for a single actor.
        :return: Size, in bytes
        """
        return _ACTOR_DATA_SIZE

    @classmethod
    def n_data_entries_per_actor(cls) -> int:
        """
        获取单个参与者在输入数组中的条目数量。

        注意：此函数不等同于`data_size_per_actor`，因为数组条目是64位整数。

        :return: 条目数量

        Get the number of entries in the input array for a single actor.

        Note: This function is NOT equivalent to `data_size_per_actor`.
        This is because array entries are 64-bit integers.
        :return: Number of entries
        """
        # 每个条目为8字节（64位），因此条目数 = 数据大小 / 8
        return _ACTOR_DATA_SIZE // 8

    # ==============================================================================================
    # 对象接口
    # Object interface

    def __hash__(self) -> int:  # type: ignore
        # 输入的哈希值基于其原始字节数据的哈希
        # hash of input is a hash of input data, registers and memory
        h = hash(self.tobytes())
        return h

    def __str__(self) -> str:
        return str(self.seed)

    def __repr__(self) -> str:
        return str(self.seed)

    def set_actor_data(self, actor_id: 'ActorID', data: UINT_NDARRAY) -> None:
        """
        设置单个参与者的数据。

        :param actor_id: 参与者ID
        :param data: 要设置的数据数组
        :raises AssertionError: 如果数据数组形状不符合预期

        Set the data for a single actor.
        :param actor_id: The actor ID
        :param data: The data to set
        :return: None
        :raises AssertionError: If the data array has an unexpected shape
        """
        assert data.shape == (self.itemsize // 8,), \
            "Data shape does not match the expected shape"

        # 复制数据到对应参与者的_ActorInput结构
        # copy the data
        self[actor_id] = data.view(_ActorInput)

        # 将padding区域填充为零（padding不被化）
        # zero-fill the unused parts of the input
        self[actor_id]['padding'] = 0

    def save(self, path: str) -> None:
        """
        将输入数据保存到二进制文件。

        :param path: 文件路径

        Save the input to a binary file.
        :param path: The path to the file
        """

        with open(path, 'wb') as f:
            f.write(self.tobytes())

    def load(self, path: str) -> None:
        """
        从二进制文件加载输入数据。

        :param path: 文件路径

        Load the input from a binary file.
        :param path: The path to the file
        """

        with open(path, 'rb') as f:
            # 读取文件为64位无符号整数数组
            contents = np.fromfile(f, dtype=np.uint64)
            n_actors = self.shape[0]
            # 逐参与者加载数据
            for actor_id in range(n_actors):
                actor_start = actor_id * self.itemsize // 8
                actor_end = actor_start + self.itemsize // 8
                self.linear_view(actor_id)[:] = contents[actor_start:actor_end]

    def linear_view(self, actor_id: ActorID) -> UINT_NDARRAY:
        """
        获取单个参与者输入数据的线性视图，即1维64位整数数组。

        :param actor_id: 参与者ID
        :return: 该参与者输入数据的线性视图

        Get a linear view of the input for a single actor;
        that is, a 1D array of 64-bit integers.
        :param actor_id: The actor ID
        :return: A linear view of the input for the actor
        """
        # 将结构化数组视图转换为纯64位整数1维数组视图
        view: UINT_NDARRAY = self[actor_id].view((np.uint64, self[actor_id].itemsize // 8))
        return view


def save_input_sequence_as_rdbf(inputs: List[InputData], path: str) -> None:
    """
    将输入序列保存为RDBF格式的文件。
    RDBF格式详见docs/devel/binary-formats.md。

    文件结构：
    1. 头部：参与者数量、输入数量
    2. 元数据：每个参与者的数据大小和保留字段
    3. 数据：所有输入的原始字节数据

    :param inputs: 输入序列
    :param path: RCBF文件的保存路径

    Save the input sequences into an RDBF-formatted file.
    (see docs/devel/binary-formats.md for details on RDBF format).

    :param inputs: The input sequence
    :param path: The path to save the RDBF file to
    :return: None
    """
    n_actors = len(inputs[0]) if len(inputs) > 0 else 1
    with open(path, 'wb') as f:
        # 头部信息：参与者数量和输入数量
        # header
        f.write((n_actors).to_bytes(8, byteorder='little'))  # number of actors
        f.write((len(inputs)).to_bytes(8, byteorder='little'))  # number of inputs

        # 元数据：每个参与者的数据大小和保留字段
        # metadata
        data_size_per_actor_bytes = InputData.data_size_per_actor()
        for _ in range(n_actors):
            f.write((data_size_per_actor_bytes).to_bytes(8, byteorder='little'))  # size
            f.write((0).to_bytes(8, byteorder='little'))  # reserved

        # 数据：逐输入写入原始字节
        # data
        for input_ in inputs:
            f.write(input_.tobytes())


# ==================================================================================================
# 输入污点标记
# Input taint
# ==================================================================================================

BOOL_NDARRAY = np.ndarray[Tuple[int], np.dtype[np.bool_]]

# _ActorInputTaint数据类型：与_ActorInput结构相同但使用布尔类型
# 用于标记每个输入元素是否被污点（影响合约追踪）
_ActorInputTaint = np.dtype(
    [
        ('main', np.bool_, _ActorInput['main'].shape[0]),
        ('faulty', np.bool_, _ActorInput['faulty'].shape[0]),
        ('gpr', np.bool_, _ActorInput['gpr'].shape[0]),
        ('simd', np.bool_, _ActorInput['simd'].shape[0]),
        ('padding', np.bool_, _ActorInput['padding'].shape[0]),
    ],
    align=False,
)


class InputTaint(BOOL_NDARRAY):
    """
    表示单个测试用例输入污点状态的固定大小布尔数组。

    数组布局与InputData类相同，元素数量一致。
    如果元素为True，则Input数组中对应元素被视为污点（影响合约追踪结果）。

    该数组用于指示哪些输入元素影响了合约追踪。

    Fixed-size boolean array that represents the taint status of a single test case input.
    The array layout is identical to the Input class, with the same number of elements.
    If an element is True, the corresponding element in the Input array is considered tainted.

    The array is used to indicate which input elements influence contract traces.
    """

    per_actor_taint_size: int = _ActorInputTaint.itemsize
    """ 单个参与者的污点区域大小 """

    def __new__(cls, n_actors: int = 1) -> InputTaint:
        """
        创建指定参与者数量的污点数组，初始全部为False。

        :param n_actors: 参与者数量，默认为1
        :return: InputTaint对象
        """
        obj = super().__new__(cls, (n_actors,), _ActorInputTaint, None, 0, None, None)
        # 初始化所有污点标记为False（未被污点）
        obj.fill(False)
        return obj

    def __array_finalize__(self, obj: Optional[UINT_NDARRAY]) -> None:  # type: ignore
        # numpy数组继承所需的finalize方法
        # if obj is None:
        #     return
        pass

    def linear_view(self, actor_id: 'ActorID') -> BOOL_NDARRAY:
        """
        获取单个参与者污点数据的线性视图，即1维布尔数组。

        :param actor_id: 参与者ID
        :return: 该参与者污点数据的线性视图

        Get a linear view of the taint for a single actor;
        that is, a 1D array of booleans.
        :param actor_id: The actor ID
        :return: A linear view of the taint for the actor
        """
        view: BOOL_NDARRAY = self[actor_id].view((np.bool_, self[actor_id].itemsize))
        return view

    def full_linear_view(self) -> np.ndarray[Tuple[int, ...], np.dtype[np.bool_]]:
        """
        获取所有参与者污点数据的完整线性视图，即1维布尔数组。

        :return: 所有参与者污点数据的线性视图

        Get a linear view of the taint for all actors;
        that is, a 1D array of booleans.
        :return: A linear view of the taint for all actors
        """
        view = self.view(np.bool_)
        return view

    def taint_actor_offsets(self, actor_id: 'ActorID', offsets: List[int]) -> None:
        """
        将单个参与者输入中指定偏移量列表的位置标记为污点。
        偏移量在_ActorInput结构中的位置指定。

        :param actor_id: 参与者ID
        :param offsets: 要标记为污点的偏移量列表

        Taint a list of locations in the input of a single actor as tainted. The locations are
        specified as offsets in the _ActorInput structure.
        :param actor_id: The actor ID
        :param offsets: A list of offsets
        :return: None
        """
        actor_view = self.linear_view(actor_id)
        for offset in offsets:
            actor_view[offset] = True

    @classmethod
    def taint_offset_from_sandbox_address(cls, sb_address: int) -> int:
        """
        此函数用于解决沙箱布局(sandbox.py)与InputTaint布局(本类)之间的不一致。

        函数从给定的沙箱地址计算InputTaint结构中的偏移量，
        通过减去缺失的padding区域来调整。

        计算过程：
        1. 根据每个参与者的沙箱大小确定参与者ID
        2. 计算沙箱内偏移量
        3. 减去MAIN区域大小（因为污点不追踪MAIN区域）
        4. 转换为8字节单位偏移 + 参与者基础偏移

        :param sb_address: 沙箱地址
        :return: InputTaint结构中的偏移量

        This function exists to cover the mismatch between the sandbox layout (sandbox.py) and
        the InputTaint layout (this class).

        The function computes the offset in the InputTaint structure from a given sandbox address
        by subtracting the missing padding.

        :param sb_address: The sandbox address
        :return: The offset in the InputTaint structure
        """
        # 计算每个参与者的沙箱大小
        per_actor_sandbox_size = SandboxLayout.data_size_per_actor()
        # 根据沙箱地址确定参与者ID和沙箱内偏移量
        actor_id = sb_address // per_actor_sandbox_size
        sandbox_offset = sb_address % per_actor_sandbox_size
        # 减去MAIN区域大小，转换为8字节单位偏移，加上参与者基础偏移
        taint_offset = sandbox_offset - SandboxLayout.data_area_size(DataArea.MAIN)
        return taint_offset // 8 + (actor_id * cls.per_actor_taint_size)
